# Generated by Django 2.1.4 on 2019-04-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artevenue', '0009_auto_20190322_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher_error',
            fields=[
                ('row_id', models.IntegerField(null=True)),
                ('publisher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(default='', max_length=256)),
                ('error', models.CharField(max_length=2000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_image_category_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(null=True)),
                ('category_name', models.CharField(max_length=128, null=True)),
                ('error', models.CharField(max_length=2000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_image_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('error', models.CharField(max_length=2000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_image_stock_image_category_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(null=True)),
                ('stock_image_category', models.CharField(max_length=128, null=True)),
                ('error', models.CharField(max_length=2000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
